config/routes.rb
Rails.application.routes.draw do

  resources :brunches do
    resources :reviews
  end

  root 'brunches#index'

end

app/models/brunch.rb
class Brunch < ActiveRecord::Base

  has_many :reviews
  # belongs_to :user

  has_attached_file :avatar, :styles =>
    { :medium => "300x300>", :thumb => "100x100>" },
    :default_url => "/images/missing.png"
  validates_attachment_content_type :avatar,
    :content_type => /\Aimage\/.*\Z/

  def average_rating
    ratings = self.reviews.map { |r| r.rating }
    sum = ratings.sum
    number_of_items = ratings.length
    result = (sum / number_of_items.to_f).round(1)
    return result
  end

end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :brunch
  # belongs_to :user

  validate :validate_rating

  def validate_rating
    if rating < 0 || rating > 5
      errors.add(:rating, "Sorry, a rating must be between 0 and 5 (inclusive), your rating is off the chart!")
    else
      return true
    end
  end

end

app/controllers/application_controller.rb
 class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/brunches_controller.rb
class BrunchesController < ApplicationController
  before_action :set_brunch, only: [:show, :edit, :update, :destroy]

  # GET /brunches
  # GET /brunches.json
  def index
    @brunches = Brunch.all
  end

  # GET /brunches/1
  # GET /brunches/1.json
  def show
    @review = Review.new
    @average_rating = @brunch.average_rating
  end

  # GET /brunches/new
  def new
    @brunch = Brunch.new
  end

  # GET /brunches/1/edit
  def edit
  end

  # POST /brunches
  # POST /brunches.json
  def create
    @brunch = Brunch.new(brunch_params)

    respond_to do |format|
      if @brunch.save
        format.html { redirect_to @brunch, notice: 'Brunch was successfully created.' }
        format.json { render :show, status: :created, location: @brunch }
      else
        format.html { render :new }
        format.json { render json: @brunch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brunches/1
  # PATCH/PUT /brunches/1.json
  def update
    respond_to do |format|
      if @brunch.update(brunch_params)
        format.html { redirect_to @brunch, notice: 'Brunch was successfully updated.' }
        format.json { render :show, status: :ok, location: @brunch }
      else
        format.html { render :edit }
        format.json { render json: @brunch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brunches/1
  # DELETE /brunches/1.json
  def destroy
    @brunch.destroy
    respond_to do |format|
      format.html { redirect_to brunches_url, notice: 'Brunch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brunch
      @brunch = Brunch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brunch_params
      params.require(:brunch).permit(:name, :opening_time, :closing_time, :vegetarian_options_available, :address, :avatar)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @brunch = @review.brunch
  end

  # GET /reviews/new
  def new
    @brunch = Brunch.find(params[:brunch_id])
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @brunch = Brunch.find(params[:brunch_id])
    @review.brunch_id = @brunch.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to brunch_path(params[:brunch_id]), notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render 'brunches/show' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:title, :content, :rating, :user_id, :brunch_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brunches_helper.rb
module BrunchesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/brunches/_form.html.erb
<%= form_for(@brunch, :html => { multipart: true  }) do |f| %>
  <% if @brunch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brunch.errors.count, "error") %> prohibited this brunch from being saved:</h2>

      <ul>
      <% @brunch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :opening_time %><br>
    <%= f.time_select :opening_time %>
  </div>
  <div class="field">
    <%= f.label :closing_time %><br>
    <%= f.time_select :closing_time %>
  </div>
  <div class="field">
    <%= f.label :vegetarian_options_available %><br>
    <%= f.check_box :vegetarian_options_available %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brunches/edit.html.erb
<h1>Editing Brunch</h1>

<%= render 'form' %>

<%= link_to 'Show', @brunch %> |
<%= link_to 'Back', brunches_path %>

app/views/brunches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Brunches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Opening time</th>
      <th>Closing time</th>
      <th>Vegetarian options available</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brunches.each do |brunch| %>
      <tr>
        <td><%= brunch.name %></td>
        <td><%= brunch.opening_time %></td>
        <td><%= brunch.closing_time %></td>
        <td><%= brunch.vegetarian_options_available %></td>
        <td><%= brunch.address %></td>
        <td><%= link_to 'Show', brunch %></td>
        <td><%= link_to 'Edit', edit_brunch_path(brunch) %></td>
        <td><%= link_to 'Destroy', brunch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brunch', new_brunch_path %>

app/views/brunches/new.html.erb
<h1>New Brunch</h1>

<%= render 'form' %>

<%= link_to 'Back', brunches_path %>

app/views/brunches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @brunch.name %>
</p>

<p>
  <strong>Opening time:</strong>
  <%= @brunch.opening_time %>
</p>

<p>
  <strong>Closing time:</strong>
  <%= @brunch.closing_time %>
</p>

<p>
  <strong>Vegetarian options available:</strong>
  <%= @brunch.vegetarian_options_available %>
</p>

<p>
  <strong>Address:</strong>
  <%= @brunch.address %>
</p>

<%= image_tag @brunch.avatar.url %>

<p>
  <strong>Average rating:</strong>
  <%= @average_rating %>
</p>
<!-- Add in all of our reviews -->
<hr>

<%= render 'reviews/form' %>

<p>
  <strong>Reviews</strong>
</p>

<% @brunch.reviews.each do |review| %>
  <tr>
    <td><%= review.title %></td>
    <td>Rating: <%= review.rating %>/5</td>
    <td><%= review.content %></td>
  </tr>
  <br>
  <br>
<% end %>

<hr>

<%= link_to 'Edit', edit_brunch_path(@brunch) %> |
<%= link_to 'Back', brunches_path %>
<%= link_to 'New review', new_brunch_review_path(@brunch) %>

<!-- Here add in a link to create a new review -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BrunchApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reviews/_form.html.erb
<%= form_for([@brunch, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Rating</th>
      <th>User</th>
      <th>Brunch</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.title %></td>
        <td><%= review.content %></td>
        <td><%= review.rating %></td>
        <td><%= review.user_id %></td>
        <td><%= review.brunch_id %></td>
        <td><%= link_to 'Show', brunch_review_path(review.brunch, review) %></td>
        <td><%= link_to 'Edit', edit_brunch_review_path(review.brunch, review) %></td>
        <td><%= link_to 'Destroy', brunch_review_path(review.brunch, review), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', brunch_reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @review.content %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>User:</strong>
  <%= @review.user_id %>
</p>

<p>
  <strong>Brunch:</strong>
  <%= @review.brunch_id %>
</p>

<% if @review.rating > @brunch.average_rating %>
  <p>You rated this brunch place higher than average!</p>
<% else %>
  <p>You rated this brunch place lower than average!</p>
<% end %>

<%= link_to 'Edit', edit_brunch_review_path(@review.brunch, @review) %> |
<%= link_to 'Back', brunch_reviews_path(@review.brunch) %>